# On dit à Gitpod d'utiliser notre boîte à outils personnalisée.
image:
  file:.gitpod.Dockerfile

# On configure les "portes" de communication de notre application.
ports:
  # Porte pour l'API REST (pour envoyer des requêtes à la blockchain)
  - name: API-REST
    port: 1317
    onOpen: ignore
    visibility: public
  # Porte pour gRPC (communication haute performance)
  - name: gRPC
    port: 9090
    onOpen: ignore
    visibility: public
  # Porte pour le RPC (communication de bas niveau)
  - name: RPC
    port: 26657
    onOpen: ignore
    visibility: public

# On définit la liste des tâches à exécuter.
tasks:
  - name: Blockchain Setup & Run
    # 'init' : Tâches de préparation (exécutées en arrière-plan avant même que vous n'ouvriez le projet)
   init: |
  if [! -f ".scaffolded" ]; then
    echo "Création du squelette de la blockchain 'francegouvernance'..."
    ignite scaffold chain francegouvernance --address-prefix francegouvernance
    touch .scaffolded
  else
    echo "La blockchain est déjà créée. On passe cette étape."
  fi
  
  cd francegouvernance
  echo "Installation des dépendances Go..."
  go mod tidy
      
    # 'command' : Tâche principale (exécutée quand vous ouvrez le projet)
    command: |
      # On va dans le dossier de la blockchain.
      cd mychain
      # On démarre le serveur de la blockchain.
      ignite chain serve
